#!/bin/bash

path_test=/Users/ggordon_apple/project/shared-reference/shareRef/test/unit/shareref

array=(
Interview
InterviewMethod
InterviewType
InterviewState
Invitation
Employer
EmployerLocation
EmployeeLocation
Employee
EmployeeHistory
State
Location
ProspectEmployer
ShareReference
EmployeeReference
)

suffix=Spec.groovy
for domain in ${array[*]} 
do
   if [ ! -f "$path_test/$domain$suffix" ]; then
         grails create-domain-class $domain
         grails generate-controller $domain
         grails generate-views $domain
   fi 
done

